name: Check Changed Packages
description: 'Checks whether any files in the specified packages were changed in the current commit'
inputs:
  commit:
    description: 'Commit to check files against'
    required: true
  packages:
    description: 'List of packages to check for changes'
    required: true
outputs:
  any-package-changed:
    description: 'Boolean indicating whether any packages were changed'
    value: ${{ steps.check-changed-packages.outputs.has-changed-packages}}
runs:
  using: 'composite'
  steps:
    - name: Determine if there were changes in the given packages
      shell: bash
      id: check-changed-packages
      run: |
        # stores the names of changed packages
        changed_packages=()

        changed_files=$(echo git diff --name-only ${{ inputs.commit }}~..${{ inputs.commit }})

        # stores package names concatenated with pipe
        packages=$(echo "${{ inputs.packages }}" | sed 's/\s/|/g')      

        if echo "$changed_files" | grep -Eq "^($packages)/"; then
          echo "has-changed-packages=true" >> $GITHUB_OUTPUT
        else
          echo "has-changed-packages=false" >> $GITHUB_OUTPUT
        fi
