name: Build and Runtime Test Detox Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

      - name: Install e2e packages
        run: yarn workspace e2e install --no-lockfile --network-timeout 60000

      - run: yarn e2e detox:build:android
      - run: yarn e2e detox:e2e:android
