name: Build and Runtime Test Detox iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install e2e packages
        uses: ./.github/actions/install-with-retries
        with:
          no-lockfile: true
          working-directory: ./packages/e2e
          skip-cypress-binary: true

      - name: Cache CocoaPods
        uses: actions/cache@v3
        id: podcache
        with:
          path: examples/react-native/ios/Pods
          key: pods-${{ hashFiles('examples/react-native/ios/Podfile.lock') }}
          restore-keys: |
                        pods-${{ hashFiles('examples/react-native/ios/Podfile.lock') }}
                        pods-
        continue-on-error: true
    
      - name: Update CocoaPods
        run: |
          gem update cocoapods xcodeproj
          cd examples/react-native/ios && pod install && cd ../../..

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn detox:build:ios
      - run: yarn detox:e2e:ios
