name: POC e2e Detox Android

on: push

jobs:
  e2e:
    # Only run e2e tests if unit tests pass
    runs-on: macos-latest
    environment: ci
    env:
      NODE_ENV: test
      
    steps:  
          
      - name: Install emulator
        run: |
          sysctl kern.hv_support
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-27;default;x86_64"
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name Pixel_5_API_27 --device "pixel_5" --abi x86_64 --package "system-images;android-27;default;x86_64"
     
      - name: Start Android emulator
        run: |
          nohup $ANDROID_HOME/tools/emulator -verbose -avd Pixel_5_API_27 -no-boot-anim -no-audio -no-snapshot-load -accel on -gpu host -qemu -m 4096 &
          $ANDROID_HOME/platform-tools/adb wait-for-device
          $ANDROID_HOME/platform-tools/adb devices
          sleep 45
          screencapture screenshot.jpg
          $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png
          
      - name: Upload emulator screenshot
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2 https://github.com/actions/upload-artifact/commit/0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: android-e2e-emulator
          path: |
            emulator.png
          retention-days: 5

       

