name: POC e2e Detox Android

on: push

jobs:
  e2e:
    # Only run e2e tests if unit tests pass
    runs-on: macos-latest
    environment: ci
    env:
      NODE_ENV: test
      
    steps:  
     - name: Install emulator
       run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install emulator
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-31;default;x86_64"
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --name Pixel_2_API_31 --device "pixel_2" -k "system-images;android-31;default;x86_64"

     - name: List avds
       run: $ANDROID_HOME/emulator/emulator -list-avds
       
     - name: Launch emulator
       run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_2_API_31 -no-window -no-audio &
          adb wait-for-device
