on: pull_request

jobs:
  check-changed-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # For `pull_request_target`, we want ref to point to `pull_request.head.ref` because `github.ref`
          # always points to the target branch.
          # See: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.repository }}
          persist-credentials: false

      - name: Determine changes
        uses: ./.github/actions/changed-packages
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          packages: 'packages/react-native,packages/react-core,packages/ui'

  e2e-ios:
    needs: check-changed-packages 
    if: ${{ needs.check-changed-packages.outputs.has-changed-packages == 'true' }}
    runs-on: macos-latest
    steps:
      - name: Running ios e2e
        run: |
           echo "Running e2e tests, RN packages were modified!"
        
  
