# Description: This workflow automatically adds a `pending-triage` label to issues that need attention
#
# Triggered by: newly opened, re-opened or transferred issues

name: Label new issues

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  label_issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Add pending-triage label
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue edit $ISSUE_NUMBER --add-label 'pending-triage'
